version: 2.1
jobs:
  bobby:
    docker:
      - image: znck/pnpm:latest
    steps:
      - checkout
      - run: echo "A first hello"
  sally:
    docker:
      - image: znck/pnpm:latest
    steps:
      - checkout
      - run: echo "Double trouble"
workflows:
  bobby_sally:
    jobs:
      - bobby
      - sally