version: 2.1
jobs:
  build:
    docker:
      - image: ianwalter/pnpm:latest
    steps:
      - checkout
      - run: echo "pnpm installing"
      - run: pnpm install
      - run: CI=true pnpm run build
  test:
    docker:
      - image: ianwalter/pnpm:latest
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: pnpm install
      - run: pnpm test -- --coverage --updateSnapshot
  hithere:
    docker:
      - image: ianwalter/pnpm:latest
    steps:
      - checkout
      - run: echo "helllooooo!"
workflows:
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
